version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: errantdns-postgres
    environment:
      POSTGRES_DB: dnsdb
      POSTGRES_USER: dnsuser
      POSTGRES_PASSWORD: dnspass
    ports:
      - "5432:5432"
    volumes:
      - errantdns_data:/var/lib/postgresql/data
      - .schemas/postgresql.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  errantdns_data:
